### ISSUE TITLE
OSGI Start error

### ISSUE THREAD

**Issue by rahooftkh** [icreated/webstore-api#3]
how can i integrate webstore-api with idempiere

added webstore code to idempiere workspace and add jar to osgi packages
but when start package got an error

org.osgi.framework.BundleException: Could not resolve module: org.icreated.wstore.api [336]
Unresolved requirement: Import-Package: org.glassfish.jersey.client; version="2.22.1"

at org.eclipse.osgi.container.Module.start(Module.java:451)
at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:431)
at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:450)
at org.apache.felix.webconsole.internal.core.InstallHelper.doRun(InstallHelper.java:67)
at org.apache.felix.webconsole.internal.core.BaseUpdateInstallHelper.doRun(BaseUpdateInstallHelper.java:99)
at org.apache.felix.webconsole.internal.core.BaseUpdateInstallHelper.run(BaseUpdateInstallHelper.java:171)
at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by icreated** [comment]
Have you checked jersey dependencies?

[image: image.png]

**Comment by rahooftkh** [comment]
how to add missing dependencies into idempiere??
which project's pom.xml add dependency
